homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: '/%app.locale%/main'
        permanent: true

index:
    path: /{_locale}/main
    controller: App\Controller\MainController::index
    requirements:
        _locale: '%app.locales%'
